spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update  # Esta línea es opcional, si quieres que Hibernate actualice automáticamente el esquema de la base de datos
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/sonardb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
